# Generated by Django 5.2.2 on 2026-06-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0004_interaction_history_entity_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="interactionhistory",
            new_name="interaction_entity__3cf81c_idx",
            old_name="interaction_entity_created_idx",
        ),
    ]
