# Generated by Django 5.2.2 on 2026-06-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_add_owner_to_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="cuisine",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="place",
            name="fee",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="internet_access",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="opening_hours",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="place",
            name="outdoor_seating",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="wheelchair",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
