# Generated by Django 5.2.2 on 2026-06-22 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_place_enriched_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["-is_curated", "name"]},
        ),
        migrations.AddField(
            model_name="place",
            name="is_curated",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["is_curated", "city"], name="places_is_cura_e7c8cd_idx"
            ),
        ),
    ]
