# Generated by Django 5.2.2 on 2026-06-14 04:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("people_count", models.PositiveSmallIntegerField(default=1)),
                ("city", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=120, unique=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("generated", "Generado"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("place", "Lugar"),
                            ("activity", "Actividad"),
                            ("event", "Evento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("morning", "Mañana"),
                            ("afternoon", "Tarde"),
                            ("evening", "Noche"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("note", models.TextField(blank=True, default="")),
                ("generation_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planner.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_items",
                "ordering": ["slot", "order"],
            },
        ),
    ]
