# Generated by Django 5.2.2 on 2026-06-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_plan_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plan",
            new_name="plans_user_id_705d7a_idx",
            old_name="plans_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="plan",
            new_name="plans_date_fd0c5f_idx",
            old_name="plans_date_status_idx",
        ),
    ]
